### ISSUE TITLE
[BUG] GX Task is stuck on local dockerized Airflow

### ISSUE THREAD

**Issue by itaise** [great-expectations/great_expectations#8740] opened 2023-09-20 11:44 UTC
**Describe the bug**
We are using GX widely in prod with Airflow on K8s and it works great. 
However, there is an issue in our dev environment - The dev environment is a dockerized Airflow, running on users' Mac.
Toward the end of the checkpoint run, the task is stuck for a long time - around 10-20 minutes.

We are writing the validation results to Postgres DB, and I actually see the expectation results in the DB **right away**, while the Airflow task is stuck for approx 20 minutes after it. Then, the slack action is performed. 
So - the issue is somewhere between the storage of validation results and performing the actions I guess?

This is a really problematic issue for our internal users. 
I am not sure how to pinpoint the cause of it. I saw a similiar issue opened recently (but for AWS managed Airflow) - 
https://github.com/great-expectations/great_expectations/issues/8671
 
![image](https://github.com/great-expectations/great_expectations/assets/64745584/29fdc48e-bb96-4f70-a13d-8841c836f644)

Expected Behavior - 
Task will finish quickly like in prod (Airflow on K8s). 

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 - GX Version: 0.17.17
 - GX experimental - 0.1.20230830090
 - airflow-provider-great-expectations==0.1.5
 - Airflow version 2.6.2
 - Data Source: Trino
 - Validation store - postgres 
 - Environment - Local Airflow docker.  

Thanks a lot! 
CC: @talagluck @r34ctor

**Comment by itaise** [comment] 2023-09-20 14:23
So, I found something interesting. 
When I remove the "store_evaluation_params" action it works fine. 
I guess in local mode it doesnt work for some reason

`[
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            }
        ]`

**Comment by nenkie76** [comment] 2023-09-22 07:54
@itaise , please check whether Closing comment from https://github.com/great-expectations/great_expectations/issues/8671#issuecomment-1730969372 is applicable for your case.

**Comment by rachhouse** [comment] 2023-09-27 19:59
Hi @itaise, we'll investigate this issue. In the meantime, could you provide your Checkpoint definitions?

**Comment by itaise** [comment] 2023-09-27 22:47
Hi, 
This is how the checkpoint is defined. Thanks a lot!  

```
CheckpointConfig(
            **{
                "name": f"{self.table_name}_checkpoint",
                "config_version": 1.0,
                "template_name": None,
                "module_name": "great_expectations.checkpoint",
                "class_name": "Checkpoint",
                "run_name_template": "%Y-%m-%d-%H_%M_%S-run-",
                "expectation_suite_name": "",
                "batch_request": None,
                "action_list": [
            {
                "name": "store_validation_result",
                "action": {"class_name": "StoreValidationResultAction"},
            },
            {
                "name": "store_evaluation_params",
                "action": {"class_name": "StoreEvaluationParametersAction"},
            }
        ]
                "evaluation_parameters": {},
                "runtime_configuration": {},
                "validations": [
                    {
                        "batch_request": {
                "datasource_name": datasource_name,
                "data_connector_name": "default_configured_data_connector_name",
                "data_asset_name": self.data_asset_name,
            },
                    }
                ],
            }
        )
```

**Comment by itaise** [comment] 2023-09-27 22:49
> @itaise , please check whether Closing comment from [#8671 (comment)](https://github.com/great-expectations/great_expectations/issues/8671#issuecomment-1730969372) is applicable for your case.

Its not applicable, we dont use data docs.. thanks!

**Comment by rachhouse** [comment] 2023-10-16 13:33
Hey @itaise, apologies for the delay, I had time to dig into this issue on Friday. I was able to replicate your setup as closely as possible: Mac, dockerized Airflow, dockerized Postgres for the validation store, dockerized Trino for source data, pinned versions for the cited gx packages, and a running Checkpoint with the `store_evaluation_params` action.

However, I was not able to reproduce the slow/stuck Airflow task; there was no noticeable delay in the Airflow task over a few different iterations of running the test Checkpoint. Possibly there's there's a difference in our setups or code that is at play?

If you'd like to continue to investigate this, I think what would be most helpful is capturing your current dev setup and GX workflow code (to the extent you are comfortable sharing) in a repo that reproduces the slow task, then we can run it and take another look at it on our side. Thanks!

**Comment by molliemarie** [comment] 2024-08-23 00:30
Hello @itaise. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Closed as not planned by molliemarie** 2024-08-23 00:30 UTC
