### ISSUE TITLE
`TypeError: issubclass() arg 1 must be a class` on tests that were passing the day before

### ISSUE THREAD

**Issue by Alexander-Serov** [great-expectations/great_expectations#7974] opened 2023-05-23 09:58 UTC
**Describe the bug**
We have a great expectations test that was working on `master` just yesterday, but not passing today anymore. It seems like something has changed in the upstream packages.

**To Reproduce**
 Here is the error log:
```
Traceback (most recent call last):
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/experimental/datasources/dynamic_pandas.py", line 421, in _generate_pandas_data_asset_models
    asset_model.update_forward_refs(**_TYPE_REF_LOCALS)
  File "pydantic/main.py", line 815, in pydantic.main.BaseModel.update_forward_refs
  File "pydantic/typing.py", line 553, in pydantic.typing.update_model_forward_refs
    '''Return a list containing n references to x.'''
  File "pydantic/typing.py", line 524, in pydantic.typing.update_field_forward_refs
    def __eq__(self, other):
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/miniforge3/envs/project-bug/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "project/_template/pipeline_s01.py", line 3, in <module>
    from pipeline_s11 import run as run11
  File "/Users/user/Documents/git/project/project/_template/pipeline_s11.py", line 12, in <module>
    from expectations import run_checkpoint
  File "/Users/user/Documents/git/project/project/_template/expectations.py", line 8, in <module>
    from great_expectations.checkpoint import SimpleCheckpoint
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/__init__.py", line 6, in <module>
    from great_expectations.data_context.migrator.cloud_migrator import CloudMigrator
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context import (
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/data_context/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context.abstract_data_context import (
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 112, in <module>
    from great_expectations.experimental.datasources.config import GxConfig
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/experimental/__init__.py", line 1, in <module>
    from great_expectations.experimental import datasources
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/experimental/datasources/__init__.py", line 3, in <module>
    from great_expectations.experimental.datasources.pandas_datasource import (
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/experimental/datasources/pandas_datasource.py", line 130, in <module>
    _FILESYSTEM_ASSET_MODELS = _generate_pandas_data_asset_models(
  File "/miniforge3/envs/project-bug/lib/python3.8/site-packages/great_expectations/experimental/datasources/dynamic_pandas.py", line 423, in _generate_pandas_data_asset_models
    raise DynamicAssetError(
great_expectations.experimental.datasources.dynamic_pandas.DynamicAssetError: Updating forward references for asset model CSVAsset raised TypeError: issubclass() arg 1 must be a class
```

**Expected behavior**
Find which upstream dependency changed and fix it.

**Environment (please complete the following information):**
 - Operating System:  Linux & MacOS
 - Great Expectations Version: tried `0.15.50` and `0.16.3`

**Comment by vkald** [comment] 2023-05-23 10:23
We have the same issue running great expectations from databricks.
It runs on databricks runtime 11.3 LTS, but fails on 12.2 LTS

**Comment by Alexander-Serov** [comment] 2023-05-23 11:03
Update: found a hotfix by downgrading from `typing_extensions == 4.6.0` to `typing_extensions == 4.5.0`.

Let us update GX requirements and maybe signal it to `typing_extensions`?

I even think the GX requirements have already been fixed [yesterday](https://github.com/great-expectations/great_expectations/blob/a71721076376ae66c4b2b7fda253934675ff30be/requirements.txt#L34) but have not been released yet. Can we release a bugfix?

**Comment by jacovg91** [comment] 2023-05-23 11:34
Same issue here, can't even `import great_expectations` anymore.
Getting: 
`DynamicAssetError: Updating forward references for asset model CSVAsset raised TypeError: issubclass() arg 1 must be a class`

This happened from this morning. We are also using DBR 12.2 LTS.

Edit: fix from @Alexander-Serov resolved it for us. Thanks a lot!

**Comment by lucasmengual92** [comment] 2023-05-23 11:47
We managed to solve it for DBR 12.2 LTS with versions:
```
SQLAlchemy==1.4.47
typing_extensions==4.5.0
pydantic==1.9.2
```

P.S. We run the pip installs through the init_scripts section on the cluster settings.

**Comment by vkald** [comment] 2023-05-23 11:47
seems like the problem is in pydantic that is being used by typing_extensions v4.6.0.
Seems like they are working on a bugfix for this now

**Comment by Bipinrawat1996** [comment] 2023-05-23 12:40
pip3 install typing-extensions==4.5.0 after installing this the error is resolved.

**Comment by kujaska** [comment] 2023-05-23 16:32
The complete list of versions (working in databricks now):

%pip install great_expectations==0.16.13
%pip install sqlalchemy==1.4.27
%pip install snowflake-connector-python==3.0.2
%pip install snowflake-sqlalchemy==1.4.7
%pip install typing_extensions==4.5.0 
%pip install pydantic==1.9.2

**Comment by tjholsman** [comment] 2023-05-23 17:41
Hello everyone, thanks for logging this! We have identified the same issue and are working on next steps.

For now pinning typing_extensions to 4.5 should resolve the issue as a temporary workaround:

`pip install typing_extensions==4.5.0`

**Comment by tjholsman** [comment] 2023-05-23 19:54
Hello again! This has been resolved in the [latest pydantic release](https://github.com/pydantic/pydantic/releases/tag/v1.10.8). Please update pydantic to the latest release and it should resolve this issue in GX. 

Please let us know if you run into anything else!

**Closed as completed by tjholsman** 2023-05-23 19:54 UTC
Labels: community
