### ISSUE TITLE
Issue in expect_column_values_to_match_regex 

### ISSUE THREAD

**Issue by abhinav2341** [great-expectations/great_expectations#7743] opened 2023-04-27 06:46 UTC
I am trying to perform an expectation to match a regex , i am using postgres sql as my datasource . i am facing issue with my regex . for instance i am validating email for which i am using `^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$`  as a regular expression in my expectation json . i have to use \\ escape character in json to keep it valid but when it perform the data quality operation - ```
SELECT pk1,pk2,pk3
FROM public.tablename 
WHERE email IS NOT NULL AND NOT (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$'); 
``` It is using incorrect regex . as you can see it should use` ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ `but it is using `^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$`

1. Setup GE with postgres as a datasource.
2. create an expectation suite with following expectation on a email column -
```
{
        "expectation_type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "email",
          "regex": "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$"
        },
        "meta": {}
      }
```
3. when you run this expectation you will get an error indicating issue at  `\`  , if we use  `\\`  it is resolved but regex expression wont work as desired.

**Expected behavior**
i would want suite to accept '\' in regex .

**Environment:**
 - Linux
 - Great Expectations Version: 0.15.50

**Comment by austiezr** [comment] 2023-04-27 21:41
Hey @abhinav2341! Thanks for raising this.

We'll investigate and be in touch.

**Comment by schollm** [comment] 2023-05-22 20:56
To simplify the test-case:
```
{
        "expectation_type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "email",
          "regex": "\\."
        },
        "meta": {}
}
```
should match "." but none of "a",  "\\" or "\\x" (which would be matched by r"\\.")

**Comment by josectobar** [comment] 2023-07-12 23:57
Hey @abhinav2341 and @schollm, I was unable to reproduce the issue but I think I know what's going on.

I'd recommend that you use [raw](https://www.digitalocean.com/community/tutorials/python-raw-string) strings when defining regexes. This way you avoid having to deal with escaping characters:
```
{
        "expectation_type": "expect_column_values_to_match_regex",
        "kwargs": {
          "column": "email",
          "regex": r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$"
        },
        "meta": {}
      }
```

I do want to point out that the output when running this expectation will show a double backslash in that regex but that is only the visual representation of it. Let me know if this works for you.

**Comment by austiezr** [comment] 2023-07-24 15:50
Hey @abhinav2341! Closing this out for now -- if the above guidance doesn't resolve this issue for you, please feel free to re-open.

**Closed as completed by austiezr** 2023-07-24 15:50 UTC
