### ISSUE TITLE
Mean expectation for DecimalType column  unexpectedly raises an exception: TypeError: Expected numeric column type for function mean()

### ISSUE THREAD

**Issue by mbassennesm** [great-expectations/great_expectations#7744] opened 2023-04-27 12:32 UTC
I have experienced the exact same issue  as in https://github.com/great-expectations/great_expectations/issues/800 where the column mean expectation fails for a DecimalType column in PySpark. This is an expected behavior since the mean is logically defined and DecimalType is a numeric type in PySpark.

```
data = spark.createDataFrame([
    {
        "city": "New York",
        "coast": "east",
        "population": 1e6,
    },
    {
        "city": "San Francisco",
        "coast": "west",
        "population": 1e5,
    },
])

data = data.withColumn("population", F.col("population").cast("decimal"))

data.printSchema()
```

GX successfully validates the column as DecimalType (hence the type is properly recognized), but returns the error below for the column mean expectation:

`
expect_column_mean_to_be_between raised an exception:
Expected numeric column type for function mean()
[Show exception traceback...](https://github.com/great-expectations/great_expectations/issues/800#section-5-content-block-2-cell-1-2-content-2-collapse-body-44d37fae-745e-43e2-8bb7-83d690bb7a51)

Traceback (most recent call last):
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 555, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/metric_provider.py", line 90, in inner_func
return metric_fn(*args, **kwargs)
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/column_aggregate_metric_provider.py", line 230, in inner_func
metric_aggregate = metric_fn(
File "/job/.local/lib/python3.8/site-packages/great_expectations/expectations/metrics/column_aggregate_metrics/column_mean.py", line 35, in _spark
raise TypeError("Expected numeric column type for function mean()")
TypeError: Expected numeric column type for function mean()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/job/.local/lib/python3.8/site-packages/great_expectations/validator/validation_graph.py", line 276, in _resolve
self._execution_engine.resolve_metrics(
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 290, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "/job/.local/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 559, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: Expected numeric column type for function mean()
`

_Originally posted by @mbassennesm in https://github.com/great-expectations/great_expectations/issues/800#issuecomment-1525613093_

**Comment by austiezr** [comment] 2023-04-27 21:31
Hey @mbassennesm! Thanks for raising this.

This is a known issue currently on our backlog for resolution. I'm closing this issue out for now as a duplicate of #6393; please feel free to provide any additional context on this issue.

**Closed as completed by austiezr** 2023-04-27 21:31 UTC
