### ISSUE TITLE
[BUG] expect_multicolumn_sum_to_equal outputs AttributeError / TypeError

### ISSUE THREAD

**Issue by data-han** [great-expectations/great_expectations#7453] opened 2023-03-24 17:30 UTC
**Describe the bug**
When using expect_multicolumn_sum_to_equal, it does not outputs the result as intended. Instead, it outputs an error which fails to show up in Data doc anyway.

**To Reproduce**
using expect_multicolumn_sum_to_equal 

**Expected behavior**
This should work as intended as per document, where multi columns summation should result in a value

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]: MacOS
 - Great Expectations Version: [e.g. 0.13.2]: 0.16.1

**Additional context**

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/51312880/227598423-dc69bebb-2875-4e5e-8ec8-0eecfbacb250.png">

**Comment by talagluck** [comment] 2023-03-27 15:01
Thanks for raising this @data-han! We will review and be in touch.

**Comment by data-han** [comment] 2023-06-09 12:03
any update on this?  @talagluck @austiezr

**Comment by talagluck** [comment] 2023-06-09 14:15
Hi @data-han - thanks for the ping, and apologies for the delay on this. We have reproduced this, and it is in our backlog for the engineering team to fix. We don't yet have a firm date for this, but will let you know once we have a better idea.

**Comment by suhren** [comment] 2023-08-06 09:07
I am also experiencing this on 0.16.13. Is there some suggested workaround until there is a fix? Implementing a custom expectation with the same functionality?

**Comment by Shinnnyshinshin** [comment] 2023-09-22 18:25
@data-han and @suhren thank you for bringing up this issue. The problem was caused by the fact that some Expectations were not properly using inheritance to use the renderers in the base Expectation class. The issue itself has been resolved by #8745 and #8739 will add better renderers to `ExpectMulticolumnSumToEqual`

**Closed as completed** 2023-09-22 23:58 UTC
Labels: community, devrel
