### ISSUE TITLE
Issue in Slack notifications

### ISSUE THREAD

**Issue by masfworld** [great-expectations/great_expectations#10313] opened 2024-08-30 11:13 UTC
**Describe the bug**
GX returns an error trying to send a Slack notifications.
```
  File "/Users/miguel/code/data_integrity/venv/lib/python3.12/site-packages/great_expectations/core/expectation_validation_result.py", line 522, in asset_name
    return self.meta["active_batch_definition"].data_asset_name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'data_asset_name'
```

**To Reproduce**
`great_expectations.yml`
```
config_version: 4.0
fluent_datasources:
  pg_api_datasource_readonly:
    type: postgres
    connection_string: postgresql+psycopg2://data_integrity:${XXX}@host.docker.internal:5432/api
  sf_api_datasource:
    type: snowflake
    connection_string: 
      snowflake://DATA_INTEGRITY_PROD:${DATA_INTEGRITY_SF_PASS}@XXX/XXX/XXX?warehouse=LOAD_AND_TRANSFORM&role=CORE_API_SENSITIVE_DATA_ACCESS&application=great_expectations_oss
config_variables_file_path: uncommitted/config_variables.yml
plugins_directory: plugins/
stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./var/data/expectations/
  validation_results_store:
    class_name: ValidationResultsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/
  checkpoint_store:
    class_name: CheckpointStore
  validation_definition_store:
    class_name: ValidationDefinitionStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./validation_definitions/
expectations_store_name: expectations_store
checkpoint_store_name: checkpoint_store
validation_results_store_name: validation_results_store
data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ./var/data/uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

**Expected behavior**
Slack notifiaction should be sent

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 1.0.0
 - Data Source: Pandas, PostgreSQL and Snowflake
 - Cloud environment: Local laptop

**Additional context**
Code returning the error:
```
# Create a validation
    validation_name = "_".join(['bmy_validation_definition',date_time])
    validation_definition = context.validation_definitions.add(
        gx.ValidationDefinition(
            data=batch_definition_merge, suite=suite, name=validation_name, 
        )
    )
    
    # Create the Checkpoint
    checkpoint_name = "_".join(['my_checkpoint_name',date_time])
    print(f'Validation Definition: {validation_definition}')
    checkpoint = gx.Checkpoint(
        name=checkpoint_name,
        validation_definitions=[validation_definition],
        actions=getActionLists(),
        result_format={"result_format": "COMPLETE"},
    )
    
    # Save the Checkpoint to the Data Context
    context.checkpoints.add(checkpoint)
    
    # merged_data is a Pandas Dataframe
    checkpoint.run(
        batch_parameters={"dataframe": merged_data}
    )
    
    context.build_data_docs()

def getActionLists():
    slack_webhook = os.getenv('SLACK_WEBHOOK', None)
    if not slack_webhook:
        return []
    
    return [
        # This Action sends a Slack Notification if an Expectation fails.
        gx.checkpoint.SlackNotificationAction(
            name="send_slack_notification_on_failed_expectations",
            slack_webhook=slack_webhook,
            notify_on="all",
            show_failed_expectations=False
        ),
        # This Action updates the Data Docs static website with the Validation
        #   Results after the Checkpoint is run.
        gx.checkpoint.UpdateDataDocsAction(
            name="update_all_data_docs",
        ),
    ]
```
More info in this [Slack thread](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1724832931078659)

**Comment by miguelbirdie** [comment] 2024-08-30 13:25
The issue is in this line https://github.com/great-expectations/great_expectations/blob/fb7052aa80dd8788e920b328ea74fdb818a28238/great_expectations/core/expectation_validation_result.py#L522

The problem is that `self.meta["active_batch_definition"]` contains a dictionary, not an object.
I think `return self.meta["active_batch_definition"]['data_asset_name'] should fix the issue.

More than happy to hear alternatives

**Comment by masfworld** [comment] 2024-08-30 13:26
The issue is in this line https://github.com/great-expectations/great_expectations/blob/fb7052aa80dd8788e920b328ea74fdb818a28238/great_expectations/core/expectation_validation_result.py#L522

The problem is that `self.meta["active_batch_definition"]` contains a dictionary, not an object.
I think `return self.meta["active_batch_definition"]['data_asset_name']` should fix the issue.

More than happy to hear alternatives

**Comment by nboullianne** [comment] 2024-08-30 22:16
+1 and noting that 1.0.1 does not contain the fix for this.

unfortunately there are more references that expect `run_result.meta['active_batch_definition']` to be an object (rather than the dictionary returned by `checkpoint.run()`) - so I think easiest solution is for checkpoint.run to return the batch definition object as expected

Here is a workaround that post-processes the results converting them to expected format: 
```
from great_expectations.core.id_dict import IDDict
from great_expectations.core.batch import LegacyBatchDefinition

# Workaround: run check point with no actions to capture result 
SLACK_ACTION_NAME = 'send_slack_notification_on_validation_result'
idx, mtch = next(((i,ac) for i,ac in enumerate(checkpoint.actions) if ac.name == SLACK_ACTION_NAME))
slack_action = checkpoint.actions.pop(idx)

res = checkpoint.run()

batch_def_key = 'active_batch_definition'
batch_id_key = 'batch_identifiers'

def convert_to_id_dict(item):
    item[batch_def_key].update({batch_id_key: IDDict(item[batch_def_key][batch_id_key])})

def convert_to_legacy_batch(item):
    item[batch_def_key] = LegacyBatchDefinition(**item[batch_def_key])

res_run_results = {k:v for k,v in res.run_results.items()}

for k,v in res_run_results.items():
    #fix 2: AssertionError: 
    convert_to_id_dict(res.run_results[k].meta)

    #fix 1: AttributeError: 'dict' object has no attribute 'data_asset_name'
    convert_to_legacy_batch(res.run_results[k].meta)
    
slack_action.run(res)

#OPTIONAL add back i.e. if saving 
checkpoint.actions.append(slack_action)
```

though, config_variables are not correctly rendered (not sure if that is a separate bug or a knock on effect of calling the action outside of a checkpoint)....so if anyone is using this either pass in the webhook directly or call `context.config_variables.get('my_config_variable_name')`

**Comment by adeola-ak** [comment] 2024-09-03 14:41
hello @masfworld, @nboullianne thank you for bringing this to our attention and thank you for sharing a work around with the community, @nboullianne - I will pass this to the team and keep you updated

**Comment by adeola-ak** [comment] 2024-09-04 17:58
hi @masfworld, thank you so much for the submission! i know we are also discussing this in slack, are you also able to add a new test (or update a current slack test) to catch this going forward?

**Comment by cdkini** [comment] 2024-09-05 18:14
Resolved by https://github.com/great-expectations/great_expectations/pull/10344

**Closed as completed by cdkini** 2024-09-05 18:14 UTC
Labels: bug, community-supported
